"""The as-built as pages a person reads in the repository, with no Fabrika.

Markdown, because it renders wherever the repository is browsed, and a Mermaid
diagram of the subsystems, because the forges that render Markdown render that
too. Every page links to the one above it and the ones below: the system, a
subsystem, a capability, a file, and a big file's parts. `graph.json` is the
same reading as data, and it is what the console draws from. `records/` holds
what the reader said about each file, so a refresh anywhere reads only what
changed.

Nothing here decides anything. It lays out what `asbuilt_graph` computed.
"""

from __future__ import annotations

import json
import posixpath
import re
from collections import defaultdict

from .asbuilt_graph import AsBuilt, Capability, FileNode, ReachItem, Subsystem
from .schemas import FileRecord

GENERATED = ("<!-- Generated by Fabrika from the commit named below. Regenerate it; do not edit it. -->\n\n")


def _slug(text: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-")[:60] or "item"


def _n(n: int, one: str, many: str = "") -> str:
    return f"{n:,} {one if n == 1 else (many or one + 's')}"


def _esc(text: str) -> str:
    return (text or "").replace("|", "\\|").replace("\n", " ").strip()


class _Links:
    """Where each thing's page is, relative to whichever page links to it."""

    def __init__(self, reading: AsBuilt) -> None:
        self.sub: dict[str, str] = {}
        used: set[str] = set()
        for s in reading.subsystems:
            slug = _slug(s.name or s.key)
            base, n = slug, 2
            while slug in used:
                slug = f"{base}-{n}"
                n += 1
            used.add(slug)
            self.sub[s.key] = f"subsystems/{slug}.md"
        self.cap = {c.key: f"capabilities/{c.key}.md" for c in reading.capabilities}

    @staticmethod
    def file(path: str) -> str:
        return f"files/{path}.md"

    @staticmethod
    def rel(frm: str, to: str) -> str:
        return posixpath.relpath(to, posixpath.dirname(frm) or ".")


def render(reading: AsBuilt, records: dict[str, FileRecord], *, project_name: str = "",
           contracts: dict[str, str] | None = None) -> dict[str, str]:
    """Every page of the as-built, by path under `.fabrika/as-built/`."""
    links = _Links(reading)
    pages: dict[str, str] = {}
    pages["README.md"] = _system(reading, links, project_name)
    for s in reading.subsystems:
        pages[links.sub[s.key]] = _subsystem(reading, s, links)
    for c in reading.capabilities:
        pages[links.cap[c.key]] = _capability(reading, c, links)
    for f in reading.files:
        pages[links.file(f.path)] = _file(reading, f, links)
        if f.path in records:
            pages[f"records/{f.path}.json"] = json.dumps(
                {"blob": f.blob, "contract": (contracts or {}).get(f.path, ""),
                 "record": records[f.path].model_dump(mode="json")}, indent=1, sort_keys=True) + "\n"
    pages["graph.json"] = reading.model_dump_json(indent=1) + "\n"
    pages["stamp.json"] = json.dumps({
        "commit": reading.commit, "built_at": reading.built_at, "version": reading.version,
        "files": len(reading.files), "subsystems": len(reading.subsystems),
        "capabilities": len(reading.capabilities), "cost": reading.cost,
        "coverage": reading.coverage.model_dump(mode="json", include={
            "files_listed", "files_read", "edges_confirmed", "edges_unconfirmed"}),
    }, indent=1) + "\n"
    return pages


def _stamp(reading: AsBuilt) -> str:
    return f"As built at `{reading.commit[:12]}`, read {reading.built_at[:10]}."


def _nodes(reading: AsBuilt) -> dict[str, FileNode]:
    return {f.path: f for f in reading.files}


def _deps(reading: AsBuilt) -> dict[tuple[str, str], int]:
    nodes = _nodes(reading)
    out: dict[tuple[str, str], int] = defaultdict(int)
    for e in reading.edges:
        a, b = nodes[e.source].subsystem, nodes[e.target].subsystem
        if a and b and a != b:
            out[(a, b)] += 1
    return dict(out)


def _mermaid(reading: AsBuilt) -> str:
    ids = {s.key: f"s{i}" for i, s in enumerate(reading.subsystems)}
    rows = ["```mermaid", "flowchart TD"]
    for s in reading.subsystems:
        label = (s.name or s.key).replace('"', "'")
        code = f"{s.code} · " if s.code else ""
        rows.append(f'  {ids[s.key]}["{code}{label}<br/>{len(s.files)} files · {s.lines:,} lines"]')
    for (a, b), n in sorted(_deps(reading).items()):
        if a in ids and b in ids:
            rows.append(f"  {ids[a]} -->|{n}| {ids[b]}")
    support = [ids[s.key] for s in reading.subsystems if s.role == "support"]
    if support:
        rows.append("  classDef support stroke-dasharray: 4 3,color:#5c645c")
        rows.append(f"  class {','.join(support)} support")
    rows.append("```")
    return "\n".join(rows)


def _architecture(reading: AsBuilt) -> list[str]:
    """How it runs, as a Mermaid flowchart and a list: who uses it, what runs,
    what it talks to. Arrows between processes are the route calls code matched."""
    a = reading.architecture
    if a is None or not a.runtimes:
        return []
    code = {s.key: s.code or s.key for s in reading.subsystems}
    cap_code = {c.key: c.code or c.name for c in reading.capabilities}
    q = lambda t: (t or "").replace('"', "'")  # noqa: E731
    rows = ["```mermaid", "flowchart LR"]
    for i, x in enumerate(a.actors):
        rows.append(f'  a{i}(["{q(x.name)}"])')
    for r in a.runtimes:
        rows.append(f'  r_{_mid(r.key)}["{q(r.name)}<br/>{" · ".join(code[k] for k in r.subsystems)}"]')
    # What builds and ships it is listed under the picture, not drawn in it.
    beside = [o for o in a.outside if not o.tooling]
    for o in beside:
        shape = f'[("{q(o.name)}")]' if o.kind == "datastore" else f'["{q(o.name)}"]'
        rows.append(f"  o_{_mid(o.key)}{shape}")
    for i, x in enumerate(a.actors):
        for r in x.enters:
            rows.append(f"  a{i} --> r_{_mid(r)}")
    for l in a.links:
        arrow = "-->" if l.confirmed else "-.->"
        rows.append(f'  r_{_mid(l.source)} {arrow}|"{"HTTP" if l.kind == "http" else "starts"} · {l.count}"| r_{_mid(l.target)}')
    for o in beside:
        for r in o.runtimes:
            rows.append(f"  r_{_mid(r)} {'-->' if o.evidence == 'code' else '-.->'} o_{_mid(o.key)}")
        runs_in = {x.key for w in reading.ways_in if w.id in o.calls_in for x in a.runtimes
                   if (reading.file(w.file) or FileNode(path="")).subsystem in x.subsystems}
        for run in sorted(runs_in):
            rows.append(f'  o_{_mid(o.key)} -->|"calls in"| r_{_mid(run)}')
    rows.append("```")
    out = ["## How it runs", "", "\n".join(rows), "",
           "Solid arrows between processes are route calls code matched to a route served; an outside system "
           "drawn dashed is only named in configuration or documentation.", ""]
    for r in a.runtimes:
        kinds = ", ".join(f"{n} {k}{'s' if n != 1 else ''}" for k, n in r.ways_in.items())
        out.append(f"- **{r.name}** — {r.what}. Runs {', '.join(f'`{code[k]}`' for k in r.subsystems)}"
                   + (f"; {kinds}." if kinds else "."))
    tools = [f"`{code[k]}`" for k in a.tooling] + [o.name for o in a.outside if o.tooling]
    if tools:
        out.append(f"- **Build and tooling** — {', '.join(tools)}; nothing of it runs.")
    out.append("")
    if a.actors:
        out += ["Used by " + "; ".join(f"**{x.name}** ({x.what})" + (f" — {', '.join(f'`{cap_code[c]}`' for c in x.capabilities)}"
                                                                      if x.capabilities else "") for x in a.actors) + ".", ""]
    if a.outside:
        out += ["| Outside system | For | Named by | Calls in |", "|---|---|---:|---|"]
        for o in a.outside:
            calls = ", ".join(f"`{w.split(':', 1)[-1]}`" for w in o.calls_in)
            note = " *(build and tooling)*" if o.tooling else "" if o.evidence == "code" else " *(only named)*"
            out.append(f"| {_esc(o.name)}{note} | {_esc(o.what)} | "
                       f"{_n(len(o.files), 'file')} | {calls} |")
        out.append("")
    return out


def _mid(key: str) -> str:
    return re.sub(r"[^A-Za-z0-9]", "_", key)


def _system(reading: AsBuilt, links: _Links, project_name: str) -> str:
    cov = reading.coverage
    nodes = _nodes(reading)
    title = f"{project_name} — as built" if project_name else "As built"
    out = [GENERATED + f"# {title}", "", _stamp(reading), ""]
    if reading.summary:
        out += [reading.summary, ""]
    out += [f"**{_n(len(reading.subsystems), 'subsystem')}, {_n(len(reading.capabilities), 'capability', 'capabilities')}, "
            f"{_n(len(reading.files), 'file')}.**", ""]
    if reading.start_reading:
        out += ["## Where to start reading", ""]
        for s in reading.start_reading:
            out.append(f"- [`{s['path']}`]({links.file(s['path'])}) — {s['why']}")
        out.append("")
    out += _architecture(reading)
    if reading.subsystems:
        out += ["## Subsystems", "", _mermaid(reading), "",
                "Arrows are links between files in two subsystems — imports, routes called, files started "
                "— counted. Files shared by nearly everything are listed separately and not drawn.", "",
                "| ID | Subsystem | Files | Lines | What it is for |", "|---|---|---:|---:|---|"]
        for s in reading.subsystems:
            role = " *(support)*" if s.role == "support" else ""
            out.append(f"| `{s.code}` | [{_esc(s.name)}]({links.sub[s.key]}){role} | {len(s.files)} | {s.lines:,} | {_esc(s.summary)} |")
        out.append("")
        if any(s.role == "support" for s in reading.subsystems):
            out += ["Support subsystems are the ones nothing a person does reaches: build configuration, "
                    "dependencies, the environment. They are drawn dashed.", ""]
    if reading.hubs:
        out += ["### Shared by nearly everything", ""]
        for h in reading.hubs:
            n = sum(1 for e in reading.edges if e.target == h and e.kind == "import")
            out.append(f"- [`{h}`]({links.file(h)}) — imported by {n} files. {nodes[h].purpose}")
        out.append("")
    if reading.capabilities:
        out += ["## Capabilities", ""]
        by_area: dict[str, list[Capability]] = defaultdict(list)
        for c in reading.capabilities:
            by_area[c.area or "Other"].append(c)
        for area, caps in by_area.items():
            out += [f"**{area}**", ""]
            for c in caps:
                out.append(f"- `{c.code}` [{c.name}]({links.cap[c.key]}) — {c.summary} "
                           f"*{len(c.ways_in)} ways in, {c.tested} reached by a test.*")
            out.append("")
    if reading.findings:
        out += ["## Worth knowing", ""]
        for f in reading.findings:
            out.append(f"- **{f.title}.** {f.detail}")
        out.append("")
    out += ["## Coverage of this reading", "",
            f"- {cov.files_read:,} files read of {cov.files_listed:,} in the repository at this commit."]
    if cov.skipped:
        why: dict[str, int] = defaultdict(int)
        for s in cov.skipped:
            why[s["why"]] += 1
        out.append("- Not read: " + "; ".join(f"{n:,} {w}" for w, n in sorted(why.items(), key=lambda kv: -kv[1])) + ".")
    if cov.unread:
        out.append(f"- Could not be read: {', '.join(u['path'] for u in cov.unread[:10])}"
                   + (" and more" if len(cov.unread) > 10 else "") + ".")
    out.append(f"- {cov.placed_graph + cov.placed_link:,} files placed in subsystems "
               f"({cov.placed_link} by a link that is not an import), {cov.hubs} shared, {cov.tests} tests, "
               f"{cov.aside} documents, configuration and data listed but not drawn"
               + (f"; not placed: {', '.join(f'`{p}`' for p in cov.unplaced[:8])}" if cov.unplaced else "") + ".")
    out.append(f"- {cov.edges_confirmed:,} links confirmed by code, {cov.edges_unconfirmed:,} not.")
    out += ["", "---", "", "Every number and link here is computed from the repository; names and summaries "
            "are written by a model from what each file contains. Fabrika regenerates this directory on request."]
    return "\n".join(out) + "\n"


def _subsystem(reading: AsBuilt, s: Subsystem, links: _Links) -> str:
    me = links.sub[s.key]
    nodes = _nodes(reading)
    out = [GENERATED + f"# {s.name}" + (f" `{s.code}`" if s.code else ""), "", f"[As built]({links.rel(me, 'README.md')}) › {s.name}", "",
           _stamp(reading), ""]
    if s.summary:
        out += [s.summary, ""]
    out += [f"{len(s.files)} files, {s.lines:,} lines.", "", "## Files", "",
            "| File | Lines | What it is for | Imported by |", "|---|---:|---|---:|"]
    # what someone wrote first, then what a tool made
    for p in sorted(s.files, key=lambda p: (nodes[p].generated, -nodes[p].lines)):
        n = sum(1 for e in reading.edges if e.target == p and e.kind == "import")
        made = " *(generated)*" if nodes[p].generated else ""
        out.append(f"| [`{p}`]({links.rel(me, links.file(p))}){made} | {nodes[p].lines:,} | {_esc(nodes[p].purpose)} | {n} |")
    out.append("")
    deps = _deps(reading)
    name_of = {x.key: x.name for x in reading.subsystems}
    uses = sorted(((b, n) for (a, b), n in deps.items() if a == s.key), key=lambda kv: -kv[1])
    used = sorted(((a, n) for (a, b), n in deps.items() if b == s.key), key=lambda kv: -kv[1])
    if uses:
        out += ["## Uses", ""] + [f"- [{name_of[b]}]({links.rel(me, links.sub[b])}) — {n} links" for b, n in uses] + [""]
    if used:
        out += ["## Used by", ""] + [f"- [{name_of[a]}]({links.rel(me, links.sub[a])}) — {n} links" for a, n in used] + [""]
    arch = reading.architecture
    if arch is not None:
        run = next((r for r in arch.runtimes if s.key in r.subsystems), None)
        talks = [o.name for o in arch.outside if s.key in o.subsystems]
        where = (f"Runs in **{run.name}**" if run else "Build and tooling; nothing of it runs" if s.key in arch.tooling
                 else "")
        if where or talks:
            out += ["## Where it runs", "", where + (f". Talks to {', '.join(talks)}." if talks else "."), ""]
    else:
        outside = sorted({o for p in s.files for o in nodes[p].outside})
        if outside:
            out += ["## Outside the repository", "", ", ".join(outside), ""]
    through = [c for c in reading.capabilities
               if any(r.subsystem == s.key for r in c.direct + c.in_motion)]
    if through:
        out += ["## Capabilities that pass through", ""]
        out += [f"- [{c.name}]({links.rel(me, links.cap[c.key])})" for c in through] + [""]
    tested = sum(1 for p in s.files if nodes[p].tested_by)
    out += ["## Tests", "", f"{tested} of {len(s.files)} files are reached by a test.", ""]
    return "\n".join(out)


def _reach_rows(reading: AsBuilt, items: list[ReachItem], links: _Links, me: str) -> list[str]:
    name_of = {s.key: s.name for s in reading.subsystems}
    part_name = {(p.file, p.key): p.name for p in reading.parts}
    rows = ["| Where | Subsystem | Lines |", "|---|---|---:|"]
    for r in items[:40]:
        where = f"[`{r.file}`]({links.rel(me, links.file(r.file))})"
        if r.part:
            where += f" — {part_name.get((r.file, r.part), r.part)}"
        rows.append(f"| {where} | {_esc(name_of.get(r.subsystem, ''))} | {r.lines:,} |")
    if len(items) > 40:
        rows.append(f"| … and {len(items) - 40} more | | |")
    return rows


def _capability(reading: AsBuilt, c: Capability, links: _Links) -> str:
    me = links.cap[c.key]
    ways = {w.id: w for w in reading.ways_in}
    out = [GENERATED + f"# {c.name}" + (f" `{c.code}`" if c.code else ""), "", f"[As built]({links.rel(me, 'README.md')}) › {c.name}", "",
           _stamp(reading), ""]
    if c.summary:
        out += [c.summary, ""]
    out += ["## Ways in", "", "| Way in | Handled in | Called from | Tests |", "|---|---|---|---|"]
    for wid in c.ways_in:
        w = ways[wid]
        handled = f"[`{w.file}`]({links.rel(me, links.file(w.file))})" + (f" `{w.handler}`" if w.handler else "")
        callers = ", ".join(f"`{p}`" for p in w.callers[:4]) or "no caller found"
        tests = ", ".join(f"`{p}`" for p in w.tested_by[:3]) or "—"
        out.append(f"| `{_esc((w.method + ' ' + w.name).strip())}` | {handled} | {callers} | {tests} |")
    out.append("")
    if c.direct:
        out += ["## What it does", "", "What its handlers run, and what they call directly.", ""]
        out += _reach_rows(reading, c.direct, links, me) + [""]
    if c.in_motion:
        out += ["## What it sets in motion", "", "One call further on — where the work it starts goes.", ""]
        out += _reach_rows(reading, c.in_motion, links, me) + [""]
    return "\n".join(out)


def _file(reading: AsBuilt, f: FileNode, links: _Links) -> str:
    me = links.file(f.path)
    sub = reading.subsystem_of(f.path)
    crumb = f"[As built]({links.rel(me, 'README.md')})"
    if sub:
        crumb += f" › [{sub.name}]({links.rel(me, links.sub[sub.key])})"
    out = [GENERATED + f"# `{f.path}`", "", crumb + f" › `{posixpath.basename(f.path)}`", "", _stamp(reading), ""]
    if f.purpose:
        out += [f.purpose, ""]
    if f.generated:
        out += ["> **Generated.** A tool made this file. It is read for what it says about the system; what to "
                "review is what generates it.", ""]
    where = {"graph": f"in {sub.name}" if sub else "", "link": f"in {sub.name}, placed by a link that is not an import" if sub else "",
             "hub": "shared by nearly everything", "test": "a test",
             "aside": f"{f.kind}, listed but not drawn", "none": "not placed in a subsystem"}[f.placed_by]
    out += [f"{f.lines:,} lines, {where}.", ""]
    parts = [p for p in reading.parts if p.file == f.path]
    if parts:
        out += ["## Parts", "", f"Too big to be one node, so shown in {len(parts)} parts: groups of its functions "
                "that call each other more than the rest of the file.", "",
                "| Part | Lines | Functions | Largest | Calls out · in |", "|---|---:|---:|---|---:|"]
        for p in parts:
            out.append(f"| **{_esc(p.name)}** — {_esc(p.summary)} | {p.lines:,} | {len(p.functions)} | "
                       f"`{p.key}` | {p.calls_out} · {p.calls_in} |")
        out.append("")
        name = {p.key: p.name or p.key for p in parts}
        pairs: dict[tuple[str, str], int] = defaultdict(int)
        for link in reading.part_links:
            if link.file == f.path:
                pairs[tuple(sorted((link.source, link.target)))] += link.calls
        if pairs:
            out += ["Calls between parts, both ways:", ""]
            out += [f"- {name.get(a, a)} ↔ {name.get(b, b)}: {n}"
                    for (a, b), n in sorted(pairs.items(), key=lambda kv: -kv[1])[:20]]
            out.append("")
        for p in parts:
            out += [f"### {p.name}", "", ", ".join(f"`{fn}`" for fn in p.functions), ""]
    imports = sorted(e.target for e in reading.edges if e.source == f.path and e.kind == "import")
    launches = sorted(e.target for e in reading.edges if e.source == f.path and e.kind == "launch")
    importers = sorted(e.source for e in reading.edges if e.target == f.path and e.kind == "import")
    if importers:
        out += ["## Imported by", ""] + [f"- [`{p}`]({links.rel(me, links.file(p))})" for p in importers] + [""]
    if imports:
        out += ["## Imports", ""] + [f"- [`{p}`]({links.rel(me, links.file(p))})" for p in imports] + [""]
    if launches:
        out += ["## Starts", ""] + [f"- [`{p}`]({links.rel(me, links.file(p))}) — by path, not imported" for p in launches] + [""]
    ways = [w for w in reading.ways_in if w.file == f.path]
    if ways:
        out += ["## Ways in", ""] + [f"- `{(w.method + ' ' + w.name).strip()}`" + (f" → `{w.handler}`" if w.handler else "")
                                     for w in ways] + [""]
    calls = sorted({e.target for e in reading.edges if e.source == f.path and e.kind == "route"})
    if calls:
        out += ["## Calls the back end in", ""] + [f"- [`{p}`]({links.rel(me, links.file(p))})" for p in calls] + [""]
    facts = []
    if f.entities_defined:
        facts.append("Defines " + ", ".join(f.entities_defined))
    if f.entities_written:
        facts.append("writes " + ", ".join(f.entities_written))
    if f.entities_read:
        facts.append("reads " + ", ".join(f.entities_read))
    if facts:
        out += ["## Data", "", "; ".join(facts) + ".", ""]
    if f.outside:
        out += ["## Outside the repository", "", ", ".join(f.outside), ""]
    if f.domain_terms:
        out += ["## Terms", "", ", ".join(f.domain_terms), ""]
    if not f.is_test:
        out += ["## Tests", ""]
        out += ([f"- [`{t}`]({links.rel(me, links.file(t))})" for t in f.tested_by] if f.tested_by
                else ["No test imports or calls this file."]) + [""]
    return "\n".join(out)
